/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.sourcegraph.gradle.semanticdb

import org.gradle.api.tasks.compile.JavaCompile
import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'com.sourcegraph.gradle.semanticdb.greeting' plugin.
 */
class SemanticdbGradlePluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()

        project.plugins.apply("java")

        project.plugins.apply("com.sourcegraph.gradle.semanticdb")

        println(project.plugins)
        println(project.tasks.withType(JavaCompile::class.java).size)

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
        println(project.tasks.findByName("compileJava"))


    }
}
