# JVM flags required by scip-javac to access internal javac APIs on Java 9+.
javac.jvmOptions=\
--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED,\
--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED,\
--add-exports=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED,\
--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED,\
--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
