load("@rules_java//java:defs.bzl", "java_library")

package(
    default_visibility = ["//visibility:public"],
)

java_library(
    name = "semanticdb-shared",
    srcs = glob(["src/main/java/**/*.java"]),
)
