name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  docker_test:
    runs-on: ubuntu-latest
    name: Docker CLI tests
    steps:
      - uses: actions/checkout@v4

      - name: Build Dockerised CLI
        run: docker build -t sourcegraph/scip-java:latest .

      - name: Test repos
        shell: bash
        run: |
          set -eu
          check_repo() {
            REPO=$1
            mkdir -p ".repos/$REPO"
            git clone "https://github.com/$REPO.git" ".repos/$REPO" && cd ".repos/$REPO" && git submodule update --init

            docker run -v "$PWD/.repos/$REPO:/sources" -w /sources sourcegraph/scip-java:latest scip-java index
            file ".repos/$REPO/index.scip" || (echo "$REPO SCIP index doesn't exist!"; exit 1)
          }

          sudo apt install parallel
          export -f check_repo

          parallel -j4 check_repo ::: circe/circe indeedeng/iwf-java-sdk
