name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: Tests
    strategy:
      fail-fast: false
      matrix:
        # NOTE(olafurpg) Windows is not enabled because it times out due to reasons I don't understand.
        # os: [windows-latest, ubuntu-latest]
        os: [ubuntu-latest]
        java: [11, 17, 21]
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v22
        with:
          summarize: false

      - uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Main project tests
        run: nix develop .#jdk${{ matrix.java }} --command sbt test

  docker_test:
    runs-on: ${{ matrix.os }}
    name: Docker CLI tests
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v22
        with:
          summarize: false

      - uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: Build Dockerised CLI
        run: nix develop --command bash -c "DOCKER_BUILDKIT=0 sbt cli/docker"

      - name: Test repos
        shell: bash
        run: |
          set -eu
          check_repo() {
            REPO=$1
            mkdir -p .repos/$REPO
            git clone https://github.com/$REPO.git .repos/$REPO && cd .repos/$REPO && git submodule update --init

            docker run -v $PWD/.repos/$REPO:/sources -w /sources sourcegraph/scip-java:latest scip-java index
            file .repos/$REPO/index.scip || (echo "$REPO SCIP index doesn't exist!"; exit 1)
          }

          sudo apt install parallel
          export -f check_repo

          parallel -j4 check_repo ::: circe/circe indeedeng/iwf-java-sdk

  bazel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v22
        with:
          summarize: false

      - uses: DeterminateSystems/magic-nix-cache-action@v13

      - run: nix develop --command bazelisk build //... --//semanticdb-javac:enabled=true
      - run: nix develop --command bazelisk run scip-semanticdb:bazel -- --sourceroot "$PWD"
      - run: du -h index.scip
      - run: nix develop "$GITHUB_WORKSPACE" --command bazelisk build //... --@scip_java//semanticdb-javac:enabled=true
        working-directory: examples/bazel-example
      - run: nix develop "$GITHUB_WORKSPACE" --command bazelisk run @scip_java//scip-semanticdb:bazel -- --sourceroot "$PWD"
        working-directory: examples/bazel-example
      - run: du -h index.scip
        working-directory: examples/bazel-example

  bazel_aspect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v22
        with:
          summarize: false

      - uses: DeterminateSystems/magic-nix-cache-action@v13

      - run: nix develop --command sbt build
      - run: echo "$PWD/out/bin" >> $GITHUB_PATH
      - name: Auto-index scip-java codebase
        run: |
          nix develop --command bash -c \
            'scip-java index --build-tool=bazel --bazel-scip-java-binary=$(which scip-java)'
      - run: du -h index.scip
      - name: Auto-index example/bazel-workspace
        run: |
          nix develop "$GITHUB_WORKSPACE" --command bash -c \
            'scip-java index --build-tool=bazel --bazel-scip-java-binary=$(which scip-java)'
        working-directory: examples/bazel-example
      - run: du -h index.scip
        working-directory: examples/bazel-example

  kotlin_plugin:
    runs-on: ubuntu-latest
    name: semanticdb-kotlinc
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v22
        with:
          summarize: false

      - uses: DeterminateSystems/magic-nix-cache-action@v13

      - name: semanticdb-kotlinc tests
        run: nix develop .#jdk11 --command sbt semanticdbKotlinc/test

      - name: Kotlin snapshots
        run: nix develop .#jdk11 --command sbt semanticdbKotlincMinimized/kotlincSnapshots

      - name: Check snapshot drift
        run: |
          git diff --exit-code \
            semanticdb-kotlinc/minimized/src/generatedSnapshots

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v22
        with:
          summarize: false

      - uses: DeterminateSystems/magic-nix-cache-action@v13

      - run: nix develop .#jdk11 --command sbt --client checkAll

      - name: Run sample benchmarks
        run: nix develop .#jdk11 --command sbt --client 'bench/Jmh/run -i 1 -f1 -t1 -foe true'


  maven:
    runs-on: ubuntu-latest
    name: Maven tests
    strategy:
      fail-fast: false
      matrix:
        java: [11, 17, 21]
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v22
        with:
          summarize: false

      - uses: DeterminateSystems/magic-nix-cache-action@v13

      - run: |
          nix develop .#jdk${{ matrix.java }} --command sbt build publishM2 publishLocal dumpScipJavaVersion
          echo "SCIP_JAVA_VERSION=$(cat VERSION)" >> $GITHUB_ENV
          echo "SCIP_JAVA_CLI=$PWD/out/bin/scip-java" >> $GITHUB_ENV

      - run: |
          nix develop "$GITHUB_WORKSPACE#jdk${{ matrix.java }}" --command \
            mvn clean verify -DskipTests -Dscip-java.version=$SCIP_JAVA_VERSION sourcegraph:sourcegraphDependencies
        working-directory: examples/maven-example

      - run: nix develop "$GITHUB_WORKSPACE#jdk${{ matrix.java }}" --command $SCIP_JAVA_CLI index-semanticdb target/semanticdb-targetroot
        working-directory: examples/maven-example

      - run: |
          set -e
          grep org.hamcrest target/semanticdb-targetroot/*dependencies.txt
          grep $PWD/src/main/java target/semanticdb-targetroot/*dependencies.txt
        working-directory: examples/maven-example

      - run: du -h index.scip
        working-directory: examples/maven-example
