name: Community build
on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'sbt'

      - uses: sbt/setup-sbt@v1

      - run: sbt cli/pack

      - run: |
          cd scip-java/target/pack && zip -r scip-java.zip .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: scip-java.zip
          name: scip-java-binary
          if-no-files-found: error



