name: nix flake check
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  flake-check:
    runs-on: ubuntu-latest
    name: nix flake check
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v22
        with:
          summarize: false

      - uses: DeterminateSystems/magic-nix-cache-action@v13

      - run: nix flake check -L
